---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redash.name }}
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.redash.port }}
    targetPort: {{ .Values.redash.targetPort }}
  selector:
    run: {{ .Values.redash.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redash.name }}
  labels:
    app: {{ .Values.redash.name }}
spec:
  selector:
    matchLabels:
      run: {{ .Values.redash.name }}
  replicas: 1
  template:
    metadata:
      labels:
        run: {{ .Values.redash.name }}
    spec:
      containers:
      - name: {{ .Values.redash.name }}
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1.5Gi
        envFrom:
        - configMapRef:
            name: env
        image: {{ .Values.redash.image }}
        ports:
        - containerPort: {{ .Values.redash.port }}
        volumeMounts:
{{ toYaml .Values.commonVolume.volumeMounts | indent 8 }}
          mountPath: {{ .Values.commonVolume.mountPathForRedash }} 
      volumes:
{{ toYaml .Values.commonVolume.volumes | indent 6 }}  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redash.workerName }}
  labels:
    app: {{ .Values.redash.workerName }}
spec:
  selector:
    matchLabels:
      run: {{ .Values.redash.workerName }}
  replicas: 1
  template:
    metadata:
      labels:
        run: {{ .Values.redash.workerName }}
    spec:
      containers:
      - name: scheduler
        resources:
{{ toYaml .Values.redash.workerResources | indent 10 }} 
        envFrom:
{{ toYaml .Values.redash.envFrom | indent 8 }} 
        env:
        - name: QUEUES
          value: celery
        - name: WORKERS_COUNT
          value: "1"
        image: {{ .Values.redash.image }}
        args: ["scheduler"]
      - name: scheduled-worker
        resources:
{{ toYaml .Values.redash.workerResources | indent 10 }} 
        envFrom:
{{ toYaml .Values.redash.envFrom | indent 8 }} 
        env:
        - name: QUEUES
          value: scheduled_queries
        - name: WORKERS_COUNT
          value: "1"
        image: {{ .Values.redash.image }}
        args: ["worker"]
      - name: adhoc-worker
        resources:
{{ toYaml .Values.redash.workerResources | indent 10 }} 
        envFrom:
{{ toYaml .Values.redash.envFrom | indent 8 }} 
        env:
        - name: QUEUES
          value: queries
        - name: WORKERS_COUNT
          value: "2"
        image: {{ .Values.redash.image }}
        args: ["worker"]